backend:
  name: test-repo  # LOCAL NO NETLIFY/Cloudflare deps

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "Artículos"
    folder: "content/posts"
    create: true
    slug: "{{year}}/{{month}}/{{slug}}"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Descripción", name: "description", widget: "text"}
      - {label: "Fecha", name: "date", widget: "datetime"}
      - {label: "Imagen", name: "image", widget: "image"}
      - {label: "Contenido", name: "body", widget: "markdown"}
